### ISSUE TITLE
Right channel intermittent

### ISSUE THREAD

**Issue by Mbailz** [LOM-instruments/Elektrosluch-DIY#1]
I've recently purchased and built the Electrosluch Mini City, but the right channel is a bit dodgy. Sound does come out of the right channel, but not as well as the left channel (the left channel is perfect and sounds great). I've checked all the solder and it all seems to be fine.

Any ideas what could be causing this? 

Thanks.

**Comment by LOM-instruments** [comment]
Hello there,
please contact us at support@zvukolom.org since that is our only support channel.
Please attach pictures of the bottom side of the circuit to help us debug the issue.
Regards,
Jonas

**Comment by Mbailz** [comment]
Hi Jonas, 
Thank you for your quick reply.
I'll do that.
Many thanks,
Alex

**Comment by Mbailz** [comment]
Fixed and sounding amazing!! 

Ir was down to a dodgy solder on one of the capacitors after all! Doh. 

Many thanks!

Alex
